#!/bin/bash

# Make bash fail much more aggressively on errors.
set -euo pipefail

# Make sure we can build our main container.
docker build -t platten/rust-musl-builder .

# Make sure we can build the enarx application
docker build -t rust-musl-enarx examples/enarx

# We're good.
echo 'OK. ALL TESTS PASSED.' 1>&2
