name: Test and publish image
on:
  workflow_dispatch:
    inputs:
      rust_version:
        description: 'The version of rust toolchain to build against. See https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-musl.html'
        required: true
        default: nightly-2022-04-13
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_image:
    name: Test image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Test image
        run: ./test-image
  build_and_push:
    name: Build image & push
    runs-on: ubuntu-latest
    needs:
      - test_image
    steps:
      - name: Set toolchain output
        id: toolchain_version
        run: |
          USER_INPUT=${{ github.event.inputs.rust_version }}
          echo "::set-output name=rust_version::${USER_INPUT:-"nightly-2022-04-13"}"
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build release image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            TOOLCHAIN=${{ steps.toolchain_version.outputs.rust_version }}
          tags: |
            ghcr.io/platten/rust-musl-builder:${{ steps.toolchain_version.outputs.rust_version }}
            ghcr.io/platten/rust-musl-builder:latest
          labels: |
            org.opencontainers.image.title=rust-musl-builder
            org.opencontainers.image.description=Tools for statically linked Rust programs using musl-libc
            org.opencontainers.image.url=https://github.com/platten/rust-musl-builder
            org.opencontainers.image.source=https://github.com/platten/rust-musl-builder
            net.randomhacks.rust-musl-builder.toolchain=${{ steps.toolchain_version.outputs.rust_version }}
          cache-from: type=registry,ref=ghcr.io/platten/rust-musl-builder:latest
          cache-to: type=inline
