name: Build & publish cross base image

on:
  push:
    branches:
      - main

jobs:
  build-cross-base-image:
    name: Build & publish cross base image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build cross base image
        run: docker build . -t quickwit/cross-base:x86_64-unknown-linux-musl
      - name: Push cross base image
        run: docker push quickwit/cross-base:x86_64-unknown-linux-musl
